env:
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-console: off
  indent: ['error', 4]
  linebreak-style: off
  import/prefer-default-export: off
  no-unused-vars: ['error', {'args': 'none'}]
